# Generated by Django 5.1.2 on 2024-11-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_bio_user_followers_user_following_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
