# Generated by Django 5.1.2 on 2024-11-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
